export { default as JsonInspector } from './JsonInspector.svelte';
export type {
    Change,
    ChangeKind,
    ChangeSet,
    DiffDiagnostic,
    DiffDiagnosticCode,
    DiffItemIdentity,
    DiffItemIdentityContext,
    DiffItemIdentityResolver,
    DiffItemIdentityRule,
    DiffTruncation,
    DiffTruncationReason,
    JsonInspectorHandle,
    JsonInspectorProps,
    JsonInspectorTableCellRenderer,
    JsonInspectorTableCellRendererProps,
    JsonInspectorTableColumn,
    JsonInspectorTableSort,
    JsonInspectorTableSortDirection,
    JsonInspectorView,
    JsonValidator,
    RawDiagnostic,
    RawDiagnosticCode,
    ValidationIssue,
    ValidationIssueSeverity,
} from './types.js';
